.TH "chaser::SmoothplannerParams" 3 "Tue Apr 9 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chaser::SmoothplannerParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBsafe_corridor_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Data Documentation"
.PP 
.SS "double chaser::SmoothplannerParams::safe_corridor_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
