.TH "build/CMakeFiles/feature_tests.cxx" 3 "Tue Apr 9 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/CMakeFiles/feature_tests.cxx \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBfeatures\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
.nf
405 { (void)argv; return features[argc]; }
.fi
.SH "Variable Documentation"
.PP 
.SS "const char features[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
