.TH "src/qt_ui/mainwindow.cpp" 3 "Tue Apr 9 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt_ui/mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QSettings>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
