.TH "src/build-qt_ui-Desktop-Debug/ui_mainwindow.h" 3 "Tue Apr 9 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/build-qt_ui-Desktop-Debug/ui_mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QAction>\fP
.br
\fC#include <QtGui/QApplication>\fP
.br
\fC#include <QtGui/QButtonGroup>\fP
.br
\fC#include <QtGui/QHeaderView>\fP
.br
\fC#include <QtGui/QLabel>\fP
.br
\fC#include <QtGui/QLineEdit>\fP
.br
\fC#include <QtGui/QMainWindow>\fP
.br
\fC#include <QtGui/QMenu>\fP
.br
\fC#include <QtGui/QMenuBar>\fP
.br
\fC#include <QtGui/QPushButton>\fP
.br
\fC#include <QtGui/QStatusBar>\fP
.br
\fC#include <QtGui/QTextEdit>\fP
.br
\fC#include <QtGui/QToolBar>\fP
.br
\fC#include <QtGui/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
