.TH "include/auto_chaser/Wrapper.h" 3 "Tue Apr 9 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/auto_chaser/Wrapper.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'auto_chaser/Chaser\&.h'\fP
.br
\fC#include 'auto_chaser/ObjectHandler\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWrapper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
