.TH "chaser::PreplannerParams" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chaser::PreplannerParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBd_trakcing_max\fP"
.br
.ti -1c
.RI "double \fBd_trakcing_min\fP"
.br
.ti -1c
.RI "double \fBd_trakcing_des\fP"
.br
.ti -1c
.RI "double \fBmax_azim\fP"
.br
.ti -1c
.RI "double \fBmin_azim\fP"
.br
.ti -1c
.RI "double \fBr_safe\fP"
.br
.ti -1c
.RI "double \fBmin_z\fP"
.br
.ti -1c
.RI "double \fBvs_min\fP"
.br
.ti -1c
.RI "double \fBvsf_resolution\fP"
.br
.ti -1c
.RI "double \fBd_connect_max\fP"
.br
.ti -1c
.RI "double \fBw_d\fP"
.br
.ti -1c
.RI "double \fBw_v\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Data Documentation"
.PP 
.SS "double chaser::PreplannerParams::d_connect_max"

.SS "double chaser::PreplannerParams::d_trakcing_des"

.SS "double chaser::PreplannerParams::d_trakcing_max"

.SS "double chaser::PreplannerParams::d_trakcing_min"

.SS "double chaser::PreplannerParams::max_azim"

.SS "double chaser::PreplannerParams::min_azim"

.SS "double chaser::PreplannerParams::min_z"

.SS "double chaser::PreplannerParams::r_safe"

.SS "double chaser::PreplannerParams::vs_min"

.SS "double chaser::PreplannerParams::vsf_resolution"

.SS "double chaser::PreplannerParams::w_d"

.SS "double chaser::PreplannerParams::w_v"


.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
