.TH "/home/jbs/catkin_ws/src/traj_gen_vis_developing/src/auto_chaser/Common.cpp" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jbs/catkin_ws/src/traj_gen_vis_developing/src/auto_chaser/Common.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'auto_chaser/Common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBGetCurrentWorkingDir\fP (void)"
.br
.ti -1c
.RI "vector< Point > \fBextract_pnts_from_path\fP (nav_msgs::Path path)"
.br
.ti -1c
.RI "Vector3f \fBgeo2eigen\fP (const Point &pnt)"
.br
.ti -1c
.RI "void \fBget_color_dist\fP (float dist_val, std_msgs::ColorRGBA &color, float max_plot_dist_val)"
.br
.ti -1c
.RI "void \fBget_color\fP (float x_in, float &r, float &g, float &b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "vector<Point> extract_pnts_from_path (nav_msgs::Path)"
Functions 
.PP
.nf
10                                                        {
11 
12   vector<Point> pnt_seq;
13   for(auto it = path\&.poses\&.begin(); it<path\&.poses\&.end();it++){
14     pnt_seq\&.push_back(it->pose\&.position);
15   }
16   return pnt_seq;
17 };
.fi
.SS "Vector3f geo2eigen (const Point & pnt)"

.PP
.nf
19                                     {
20 
21   return Vector3f(pnt\&.x,pnt\&.y,pnt\&.z);
22 };
.fi
.SS "void get_color (float x_in, float & r, float & g, float & b)"

.PP
.nf
51 {
52   // Only important if the number of colors is small\&. In which case the rest is
53   // still wrong anyway
54   // x = linspace(0,1,jj)' * (1-1/jj) + 1/jj;
55   //
56   const double rone = 0\&.8;
57   const double gone = 1\&.0;
58   const double bone = 1\&.0;
59   float x = x_in;
60   x = (x_in<0 ? 0 : (x>1 ? 1 : x));
61 
62   if (x<1\&. / 8\&.)
63   {
64     r = 0;
65     g = 0;
66     b = bone*(0\&.5 + (x) / (1\&. / 8\&.)*0\&.5);
67   } else if (x<3\&. / 8\&.)
68   {
69     r = 0;
70     g = gone*(x - 1\&. / 8\&.) / (3\&. / 8\&. - 1\&. / 8\&.);
71     b = bone;
72   } else if (x<5\&. / 8\&.)
73   {
74     r = rone*(x - 3\&. / 8\&.) / (5\&. / 8\&. - 3\&. / 8\&.);
75     g = gone;
76     b = (bone - (x - 3\&. / 8\&.) / (5\&. / 8\&. - 3\&. / 8\&.));
77   } else if (x<7\&. / 8\&.)
78   {
79     r = rone;
80     g = (gone - (x - 5\&. / 8\&.) / (7\&. / 8\&. - 5\&. / 8\&.));
81     b = 0;
82   } else
83   {
84     r = (rone - (x - 7\&. / 8\&.) / (1\&. - 7\&. / 8\&.)*0\&.5);
85     g = 0;
86     b = 0;
87   }
88 }
.fi
.SS "void get_color_dist (float dist_val, std_msgs::ColorRGBA & color, float max_plot_dist_val)"

.PP
.nf
25                                                                                      {
26 // error region 
27   if(dist_val<0){
28       color\&.r = 0\&.5;
29       color\&.g = 0\&.0;
30       color\&.b = 0\&.0;
31       color\&.a = 0\&.2;
32 
33   }
34 //   else if(dist_val == 0\&.2){
35 //       color\&.r = 0;
36 //       color\&.g = 0;
37 //       color\&.b = 1;
38 //   }
39   // normal region 
40   else{                   
41       color\&.r = pow(dist_val/max_plot_dist_val,3);
42       color\&.g = pow(dist_val/max_plot_dist_val,3);
43       color\&.b = pow(dist_val/max_plot_dist_val,3);
44   }
45   // plot only cells in this bound
46   if(dist_val<max_plot_dist_val)
47       color\&.a = 0\&.2;
48 };
.fi
.SS "std::string GetCurrentWorkingDir (void)"

.PP
.nf
2                                       {
3     char buff[FILENAME_MAX];
4     GetCurrentDir( buff, FILENAME_MAX );
5     std::string current_working_dir(buff);
6     return current_working_dir; 
7 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
