.TH "FieldParams" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx0\fP"
.br
.ti -1c
.RI "double \fBy0\fP"
.br
.ti -1c
.RI "double \fBz0\fP"
.br
.ti -1c
.RI "double \fBlx\fP"
.br
.ti -1c
.RI "double \fBly\fP"
.br
.ti -1c
.RI "double \fBlz\fP"
.br
.ti -1c
.RI "double \fBresolution\fP"
.br
.ti -1c
.RI "double \fBray_stride_res\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Data Documentation"
.PP 
.SS "double FieldParams::lx"

.SS "double FieldParams::ly"

.SS "double FieldParams::lz"

.SS "double FieldParams::ray_stride_res"

.SS "double FieldParams::resolution"

.SS "double FieldParams::x0"

.SS "double FieldParams::y0"

.SS "double FieldParams::z0"


.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
