.TH "/home/jbs/catkin_ws/src/traj_gen_vis_developing/src/qt_ui/main.cpp" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jbs/catkin_ws/src/traj_gen_vis_developing/src/qt_ui/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QtGui>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
.nf
6 {
7     QApplication a(argc, argv);
8     QNode qnode(argc,argv,"planner_client");
9     MainWindow w(&qnode);
10 
11     w\&.show();
12     a\&.connect(&a, SIGNAL(lastWindowClosed()), &a, SLOT(quit()));
13 
14     return a\&.exec();
15 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
