.TH "md__home_jbs_catkin_ws_src_traj_gen_vis_developing__r_e_a_d_m_e" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_jbs_catkin_ws_src_traj_gen_vis_developing__r_e_a_d_m_e \- traj_gen_vis 

.PP
\fIThis package is devoted to generate an online chasing trajectory in response to the future movement of a moving target only for a short horizon\&. It assumes that the future trajectory of target is updated with a given time interval and priori map is given in the form of Octomap\fP
.PP
.SH "1 Overview"
.PP
.PP
.SS "1\&.1 Algorithm"
.PP
.PP
.SS "1\&.2 File structure"
.PP
\fCdoxygen\fP
.PP
.SH "2 Installation"
.PP
.PP
.SS "2\&.1 Dependencies"
.PP
.SH "3 Usage"
.PP
.PP
.SS "3\&.1 Simulation without gazebo"
.PP
.SS "(1) one-shot mode"
.PP
.SS "(2)"
.PP
.SS "3\&.2 Simulation with gazebo (still developing)"
.PP
.SH "4\&. ROS \fBNode\fP API"
.PP
.PP
.SS "4\&.1 Published and subscribed topics"
.PP
.SS "4\&.2 Parameters"

