.TH "pkg" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkg \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBCATKIN_PACKAGE_PREFIX\fP = ''"
.br
.ti -1c
.RI "string \fBPROJECT_PKG_CONFIG_INCLUDE_DIRS\fP = '/home/jbs/catkin_ws/src/auto_chaser/include'"
.br
.ti -1c
.RI "string \fBPROJECT_CATKIN_DEPENDS\fP = ''"
.br
.ti -1c
.RI "string \fBPKG_CONFIG_LIBRARIES_WITH_PREFIX\fP = '\-ltraj_gen_chasing'"
.br
.ti -1c
.RI "string \fBPROJECT_NAME\fP = 'auto_chaser'"
.br
.ti -1c
.RI "string \fBPROJECT_SPACE_DIR\fP = '/home/jbs/catkin_ws/src/auto_chaser/build/devel'"
.br
.ti -1c
.RI "string \fBPROJECT_VERSION\fP = '0\&.0\&.0'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string pkg\&.CATKIN_PACKAGE_PREFIX = ''"

.SS "string pkg\&.PKG_CONFIG_LIBRARIES_WITH_PREFIX = '\-ltraj_gen_chasing'"

.SS "string pkg\&.PROJECT_CATKIN_DEPENDS = ''"

.SS "string pkg\&.PROJECT_NAME = 'auto_chaser'"

.SS "string pkg\&.PROJECT_PKG_CONFIG_INCLUDE_DIRS = '/home/jbs/catkin_ws/src/auto_chaser/include'"

.SS "string pkg\&.PROJECT_SPACE_DIR = '/home/jbs/catkin_ws/src/auto_chaser/build/devel'"

.SS "string pkg\&.PROJECT_VERSION = '0\&.0\&.0'"

.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
