.TH "/home/jbs/catkin_ws/src/traj_gen_vis_developing/include/target_manager/TargetManager.h" 3 "Wed Apr 17 2019" "Version 1.0.0" "auto_chaser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jbs/catkin_ws/src/traj_gen_vis_developing/include/target_manager/TargetManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'traj_gen/PolyTrajGen\&.h'\fP
.br
\fC#include <tf/transform_broadcaster\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTargetManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for auto_chaser from the source code\&.
